"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["src/gui.py"]
DATA_FILES = ["eye-drawing-35.jpg"]
OPTIONS = {
    "iconfile": "eyecon.icns",
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    name="OptimEYES",
)
